name: njeri
favicon: null
layout_spectrum: 0.03205030970275402
typography_spectrum: 0.5848867611493915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6060297028161585
  lightness: 0.9312099711969495
  saturation: 0.9522129939869046
  rhythmicContrast: 0.9833361722994596
purpose: []
