name: Njeri Rionge News Feed
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9055649
  brandStrength: 0.8785835
  lightness: 0.8094435
  brandColors:
    - '#1F1627'
    - '#FFFFFB'
    - '#BCBEB4'
    - '#5D5C5B'
    - '#6E80B3'
  rhythmicContrast: 0.9013491
typography_spectrum: 0.1003584
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3423271
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
