favicon: null
name: Njeri Rionge News Feed
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.9170213
  brandStrength: 0.8785835
  lightness: 0.9382979
  brandColors:
    - '#F8E69C'
    - '#E8A24D'
    - '#0F0909'
    - '#C36041'
    - '#582E1C'
  rhythmicContrast: 0.8148936
typography_spectrum: 0.1003584
layout_spectrum: 0.3423271
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
